### ISSUE TITLE
Tags are not pointing to the the correct commits

### ISSUE THREAD

**Issue by michael-simons** [quarkiverse/quarkus-neo4j#126]
I wonder if I am doing something wrong here: The release process correctly creates tags, but the commits are not on the main branch to which the tags point to.

Have a lock at `2.0.0` for example. It points to 657f65fb387b7f341867fc8965acc556dc9ddcb3

```
commit 657f65fb387b7f341867fc8965acc556dc9ddcb3 (tag: 2.0.0)
Author: GitHub Action <action@github.com>
Date:   Thu Dec 1 12:57:13 2022 +0000

    Update stable version for documentation

diff --git a/docs/modules/ROOT/pages/includes/attributes.adoc b/docs/modules/ROOT/pages/includes/attributes.adoc
index a08d7e0..367de13 100644
--- a/docs/modules/ROOT/pages/includes/attributes.adoc
+++ b/docs/modules/ROOT/pages/includes/attributes.adoc
@@ -1,5 +1,5 @@
 :quarkus-version: 2.14.2.Final
-:quarkus-neo4j-version: 1.7.1
+:quarkus-neo4j-version: 2.0.0
 :maven-version: 3.8.1+
 
 :quarkus-org-url: https://github.com/quarkusio
```

On the main the commit with the same change is 

```
commit 149aef3a9b23fd8454b049ecdb3cabd681c11d98
Author: GitHub Action <action@github.com>
Date:   Thu Dec 1 12:53:41 2022 +0000

    Update stable version for documentation

diff --git a/docs/modules/ROOT/pages/includes/attributes.adoc b/docs/modules/ROOT/pages/includes/attributes.adoc
index a08d7e0..367de13 100644
--- a/docs/modules/ROOT/pages/includes/attributes.adoc
+++ b/docs/modules/ROOT/pages/includes/attributes.adoc
@@ -1,5 +1,5 @@
 :quarkus-version: 2.14.2.Final
-:quarkus-neo4j-version: 1.7.1
+:quarkus-neo4j-version: 2.0.0
 :maven-version: 3.8.1+
 
 :quarkus-org-url: https://github.com/quarkusio
```

Can we fix that somehow @gsmet ?

**Comment by maxandersen** [comment]
@gastaldi ^

**Comment by gastaldi** [comment]
That's because the tag is overwritten in https://github.com/quarkiverse/quarkus-neo4j/blob/8a07489505140071261d031610d4be3eb5572979/.github/workflows/release.yml#LL71C18-L71C18 when the documentation is generated for the released version. 

We probably need to have a look at that part to avoid that

**Comment by gastaldi** [comment]
Note however that this is the only commit that isn't in the main branch, so I am not sure this is a major issue TBH

**Comment by gastaldi** [comment]
@vsevel take a look at https://github.com/quarkusio/quarkus/pull/31046, that may fix this issue.
