### ISSUE TITLE
[Feature Request] Align driver authentication with Kubernetes neo4j authentication

### ISSUE THREAD

**Issue by chkp-aviadl** [quarkiverse/quarkus-neo4j#168]
When initiating neo4j from Kubernetes from the official helm chart, it creates secret with `NEO4J_AUTH` variable.  
The value is in the form of: `<username>/<password>`.  
Current implementation forces the username and the password to be separated, and it would be great if we can just use this variable as is.  

My current workaround is to create another secret with the username and the password under different values. (maybe someone else have suggestion on simpler workaround as well?)

**Comment by aviadlevy** [comment]
Another better workaround (thanks to @israelstmz for the idea) is to manipulate the helm chart to create 2 separate values  

`neo4j-auth.yaml`

```golang
... Skip few lines without changes

{{- $username := printf "neo4j" | b64enc -}}
{{- $password := include "neo4j.password" . | printf "%v" | b64enc -}}
{{- $auth := include "neo4j.password" . | printf "neo4j/%v" | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secretName }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ template "neo4j.name" . }}"
    {{- include "neo4j.labels" $.Values.neo4j | indent 4 }}
type: Opaque
data:
  NEO4J_USER_NAME: "{{ $username }}"
  NEO4J_PASSWORD: "{{ $password }}" 
  NEO4J_AUTH: "{{ $auth }}"
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by michael-simons** [comment]
I'll add a corresponding property and parse that.

The driver itself requires username / password separately. 

This library has the joy of sitting in-between teams :)
