### ISSUE TITLE
Devservices won't start a container if you have one running @ localhost:7687

### ISSUE THREAD

**Issue by kdubb** [quarkiverse/quarkus-neo4j#299]
This makes it impossible to run Quarkus with a dev Neo4j if you happen to have one running for another reason.

This isn't how any other devservice implementation works, and makes it impossible to use and have other databases running (e.g. in Neo4j Desktop).

If `quarkus.neo4j.uri` is unset, then it should always boot a container. Only if the configuration has specified a uri should it attempt to use that container.

**Comment by michael-simons** [comment]
Hmm, we have it that way since its inception. But truth to be told, I was annoyed about it sometimes myself. Can start working on it in November.

**Comment by michael-simons** [comment]
Or also would accept a PR.
