### ISSUE TITLE
It doesn't save when using the toUni method

### ISSUE THREAD

**Issue by zhangpp520** [quarkiverse/quarkus-neo4j#47]
I'm trying to be familiar with this API.
I just want to save a record using the reactive style.

there are some boilerplate codes:
`Multi<Victim> victim = Multi.createFrom().resource(driver::rxSession, session -> session.writeTransaction(writeVictimTransactionWorker)).withFinalizer(ModelTest::closeSession).map(..)`

and finally we will get a Multi. when I subscribe it, everything is fine.  But I just want a save result,so I use 'toUni ' to change it to a Uni.

when I subscribe the gotten Uni, the record doesn't really saved,although it emits the result

**Comment by zhangpp520** [comment]
I have found the reason:
  When using _.toUni_ ,_.select().first(1)_ methods,after emit the element, there will be a cancel calling.
  I can use the _.collect().asList().map()_ method, but it's a little tricky. 
  Is there a better way to write saving code?

  By the way,the document is broken for now

**Comment by michael-simons** [comment]
Hi @zhangpp520 

All the reactive frameworks I know of (Mutiny, Project Reactor) emit a cancellation event when you use `first()` or similar. It's best you save all of the things coming back or directly use a `Uni`.

**Comment by michael-simons** [comment]
> By the way,the document is broken for now

i don't understand this. What exactly is broken?
