### ISSUE TITLE
Docs code snippets report an error

### ISSUE THREAD

**Issue by Thefolle** [quarkiverse/quarkus-neo4j#56]
# Docs code snippets report an error

[The Neo4j docs related to Quarkus](https://quarkiverse.github.io/quarkiverse-docs/quarkus-neo4j/dev/index.html#_creating_nodes) have broken code snippets.

What I see on most snippets is:
Unresolved include directive in modules/ROOT/pages/index.adoc - include::../../../../integration-tests/src/main/java/io/quarkus/it/neo4j/FruitResource.java[]

I use Firefox.

Could you please check?

**Comment by michael-simons** [comment]
Hmm @gastaldi do you know?

**Comment by gastaldi** [comment]
@michael-simons you need to create symbolic links under an `example` directory in the `docs/modules/ROOT` directory. See https://docs.antora.org/antora/latest/symlinks/ for more details

I created https://github.com/quarkiverse/quarkus-neo4j/pull/83 to fix this

**Comment by michael-simons** [comment]
Thanks a lot, much appreciated!
